[tool.poetry]
name = "numpy-ros"
version = "0.1.0"
description = "Seamlessly convert between ROS messages and NumPy arrays."
authors = ["Lucas Wolf <iamlucaswolf@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.20.3"
numpy-quaternion = "^2021.4.5"

[tool.poetry.dev-dependencies]
vermin = "^1.2.0"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
